on:
  pull_request:
    branches-ignore: gh-pages
  push:
    branches-ignore: gh-pages

name: Codeception Tests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: curl, mbstring, openssl, pdo, pdo_sqlite
          ini-values: memory_limit=-1, date.timezone='UTC'
          coverage: xdebug
          tools: composer:v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --no-suggest

      - name: Run tests
        run: php vendor/bin/codecept run --coverage --coverage-xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: tests/_output/coverage.xml
          verbose: true
